# Generated by Django 2.2.7 on 2019-12-13 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='deleted',
            new_name='completed',
        ),
    ]
